# Generated by Django 3.2.9 on 2022-01-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220131_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstories',
            name='time',
            field=models.TextField(default=''),
        ),
    ]
