# Generated by Django 4.0.2 on 2022-02-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newstories_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showstories',
            name='by',
            field=models.CharField(default='', max_length=200),
        ),
    ]
