# Generated by Django 3.2.9 on 2022-01-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AskStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(default='', max_length=100)),
                ('descendants', models.PositiveIntegerField(default=0)),
                ('id_news', models.PositiveIntegerField(default=0)),
                ('kids', models.TextField(default='')),
                ('score', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(default='')),
                ('time', models.TimeField()),
                ('title', models.TextField(default='')),
                ('type', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(default='', max_length=100)),
                ('id_news', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('time', models.TimeField()),
                ('title', models.TextField(default='')),
                ('type', models.CharField(default='', max_length=50)),
                ('url', models.TextField(default='')),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='NewStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(default='', max_length=100)),
                ('descendants', models.PositiveIntegerField(default=0)),
                ('id_news', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('time', models.TimeField()),
                ('title', models.TextField(default='')),
                ('type', models.CharField(default='', max_length=50)),
                ('url', models.TextField(default='')),
                ('kids', models.TextField(default='')),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ShowStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(default='', max_length=100)),
                ('descendants', models.PositiveIntegerField(default=0)),
                ('id_news', models.PositiveIntegerField(default=0)),
                ('kids', models.TextField(default='')),
                ('score', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(default='')),
                ('time', models.TimeField()),
                ('title', models.TextField(default='')),
                ('type', models.CharField(default='', max_length=50)),
                ('url', models.TextField(default='')),
            ],
        ),
    ]
