# Generated by Django 3.2.9 on 2022-01-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='askstories',
            options={'verbose_name': 'Ask storie', 'verbose_name_plural': 'Ask stories'},
        ),
        migrations.AlterModelOptions(
            name='jobstories',
            options={'verbose_name': 'Job storie', 'verbose_name_plural': 'Job stories'},
        ),
        migrations.AlterModelOptions(
            name='newstories',
            options={'verbose_name': 'New storie', 'verbose_name_plural': 'New stories'},
        ),
        migrations.AlterModelOptions(
            name='showstories',
            options={'verbose_name': 'Show storie', 'verbose_name_plural': 'Show stories'},
        ),
        migrations.RemoveField(
            model_name='jobstories',
            name='time',
        ),
        migrations.AlterField(
            model_name='askstories',
            name='time',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='newstories',
            name='time',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='showstories',
            name='time',
            field=models.TextField(default=''),
        ),
    ]
